Nama: Safira Nur Fauziah
NIM: A11.2019.11718

# Preprocessing Menggunakan Dataset Temperature and Cherry Blossom Status

In [28]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [29]:
dataset = pd.read_csv("cherry_bloom.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

x = atribut reguler
y = label

In [30]:
print(X)

[['2019/4/19' 9.0]
 ['2019/4/20' 8.9]
 ['2019/4/21' 11.5]
 ['2019/4/22' nan]
 ['2019/4/23' 12.5]
 ['2019/4/24' 16.3]
 ['2019/4/25' nan]
 ['2019/4/26' 5.8]
 ['2019/5/1' 13.0]
 ['2020/4/18' 9.5]
 ['2020/4/19' 9.7]
 ['2020/4/27' 7.5]
 ['2020/5/1' 15.2]
 ['2020/5/2' 18.8]
 ['2020/5/3' 21.2]
 ['2021/4/14' 6.5]
 ['2021/4/19' 10.6]
 ['2021/4/22' 8.7]
 ['2021/4/23' nan]]


In [31]:
print(y)

['bloom' 'scatter' 'bloom' 'scatter' 'bloom' 'full' 'scatter' 'scatter'
 'scatter' 'bloom' 'bloom' 'full' 'scatter' 'bloom' 'full' 'bloom' 'full'
 'scatter' 'scatter']


In [32]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = "mean")
imputer.fit(X[:, 1:2])
X[:, 1:2] = imputer.transform(X[:, 1:2])

In [33]:
print(X)

[['2019/4/19' 9.0]
 ['2019/4/20' 8.9]
 ['2019/4/21' 11.5]
 ['2019/4/22' 11.543749999999998]
 ['2019/4/23' 12.5]
 ['2019/4/24' 16.3]
 ['2019/4/25' 11.543749999999998]
 ['2019/4/26' 5.8]
 ['2019/5/1' 13.0]
 ['2020/4/18' 9.5]
 ['2020/4/19' 9.7]
 ['2020/4/27' 7.5]
 ['2020/5/1' 15.2]
 ['2020/5/2' 18.8]
 ['2020/5/3' 21.2]
 ['2021/4/14' 6.5]
 ['2021/4/19' 10.6]
 ['2021/4/22' 8.7]
 ['2021/4/23' 11.543749999999998]]


In [34]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [("encoder", OneHotEncoder(sparse=False), [0])], remainder = "passthrough")
X = np.array(ct.fit_transform(X))

In [35]:
print(X)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 9.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 8.9]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 11.5]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 11.543749999999998]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 12.5]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 16.3]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 11.543749999999998]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 5.8]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 13.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 9.5]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 9.7]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0

In [36]:
from sklearn.preprocessing import LabelEncoder #Khusus untuk mengencoder label
le = LabelEncoder()
y = le.fit_transform(y)

In [37]:
print(y)

[0 2 0 2 0 1 2 2 2 0 0 1 2 0 1 0 1 2 2]


In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [39]:
print(X_train)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 11.5]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 21.2]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 12.5]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 10.6]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 5.8]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 8.9]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 18.8]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 9.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  1.0 11.543749999999998]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
  0.0 8.7]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 9.5]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0

In [40]:
print(X_test)

[[0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 11.543749999999998]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 6.5]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 11.543749999999998]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 9.7]]


In [41]:
print(y_train)

[0 1 0 1 2 2 0 0 2 2 0 2 2 1 1]


In [42]:
print(y_test)

[2 0 2 0]


In [51]:
X_train= X_train.reshape(-1, 1)
X_test = X_test.reshape(-1, 1)

In [59]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 1] = sc.fit_transform(X_train[:, 1])
X_test[:, 1] = sc.transform(X_test[:, 1])

IndexError: index 1 is out of bounds for axis 1 with size 1

In [58]:
print(X_train)

[[0.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [11.5]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [21.2]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [12.5]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [10.6]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [5.8]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [8.9]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [18.8]
 [1.0]
 [0.0]
 

In [54]:
print(X_test)

[[0.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [11.543749999999998]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [6.5]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [11.543749999999998]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [9.7]]
